### ISSUE TITLE
Embed images in the fillable PDF

### ISSUE THREAD

**Issue by abuzer** [mikehaertl/php-pdftk#229]
Hi, 

Any hint on how we can embed images in the fillable PDF?

**Comment by mikehaertl** [comment]
pdftk can't add images.

**Comment by abuzer** [comment]
Any other hint of solution?

**Comment by mikehaertl** [comment]
Modififaction of PDF content (adding/removing/changing text or images) is not trivial. As far as I know only Adobe tools are able to do that. There's no library that I knew of because PDF's internal format is quite complex. If you're interested you can find some more details here: https://pdfbox.apache.org/1.8/architecture.html

**Comment by sdevore** [comment]
So the way I have done it is create a pdf from the image with it located where I want using imagemagik then use something like pdfJam to layer this new pdf on top of the one with all the fields filled in with php-pdftk
