### ISSUE TITLE
send() not working properly?

### ISSUE THREAD

**Issue by giannicolac** [mikehaertl/php-pdftk#312]
Hello. I'm using laravel 8 and when i use send() inside a controller, it doesn't seem to anything. I am checking for errors as recommended after the $result variable and there is none, and i'm printing the response (which send( ) seems to produce, as i have a .then) in the front end to obtain more info and i can only see in the console a bunch of text i would be seeing if i opened the pdf file with a text editor.
I am using apache 2, even tried disabling the deflate module. saveAs( ) works without any problems. I am using Ubuntu.

**Comment by mikehaertl** [comment]
Hmm, did you also test it with a simple PHP script without Laravel? If that works, then Laravel probably requires a different way of sending raw responses to the browser. If it doesn't work either it must be somewhere in your server config.

I would also check the reponse headers, e.g. with `curl -I https://yourdomain.com/pdf`.

**Comment by giannicolac** [comment]
Thanks for the answer. I will test these suggestions and then i will reply back.

**Comment by giannicolac** [comment]
Thank you for the suggestion. I will test it and then come back. Sorry i accidentally closed the thread.

**Comment by giannicolac** [comment]
Hi, i have tested your suggestions and i have found the following:
1) send( ) does indeed work properly without any problems if i do it through a simple php.
2) i checked the response headers using the curl command for the url to the controller, and got this:
HTTP/1.1 200 OK
ETag: "1222-WgnCkQ6k9Q0PwZtK2Tt9xTsql1w"
Content-Type: text/html; charset=utf-8
Accept-Ranges: none
Content-Length: 4642
Date: Sat, 08 Jul 2023 20:27:53 GMT
Connection: keep-alive
Keep-Alive: timeout=5
I don't know if using the url for the controller counts as the response though.
In any case i have this as my send:           
->send($filename = 'test.pdf', $inline = true, $headers = ['Content-Type' => 'application/pdf']);

**Comment by mikehaertl** [comment]
Ok, if it works without Laravel the problem is out of the scope of our library.  I'd suggest to consult their support channels or open a ticket on how to bypass their built in [response logic](https://laravel.com/docs/10.x/responses).

**Comment by turbowine** [comment]
I had a problem with send() in Laravel as well.
It took a bit of thinking, but I ultimately ended up doing this, which worked for me.

$file = 'docs/'.$fileName;
pdf->saveAs($file);
...// some code
$headers = array('Content-Type: application/pdf',);
response()->download($file, basename($file), $headers);

I saved the PDF file instead of sending it using the PDF library. Then, I used the Laravel library to ‘send’ the file.
Let me explain what I think was happening. To back up, I first looked at the PDF library’s code.
The send() function ends with this code, which does all the work:

$this->sendHeaders($headers);
readfile($this->_fileName);

It first sends HTTP headers; then the readfile() dumps the file bytes to the output.
Seeing this reminded me that HTTP headers must be sent before anything else is sent to the output.
The thing about large, complex frameworks, such as Laravel, is that you don’t often know what is happening and when. Therefore, it was quite possible that by the time the send() function was called, Laravel had already sent the headers for the page. If that were the case, the file transfer would fail, as you cannot send additional headers in the middle of the output stream, which is what the send() function might have been doing.  
Thus, I concluded that using the Laravel functions to send the file should work better than the send() function in the PDF library.   And I was right; it worked.  I conclude that the Laravel functions know how to work within the framework, ensuring that the HTTP response components are all sent in the correct order.
I hope this helps you.
