### ISSUE TITLE
burst problem

### ISSUE THREAD

**Issue by sebastienOD** [mikehaertl/php-pdftk#41]
Hi, 

don't know if it's me but burst function is not working with pattern.
In your Command class, you are using "escapeshellarg" which replace % with space, so impossible to use page_%d.pdf for example

Hope it could help

**Comment by mikehaertl** [comment]
Hmm, I could not reproduce that problem:

```
echo esacpeshellarg('ab%de');
// output:
// ab%de
```

**Comment by sebastienOD** [comment]
Ok, It's working on my online server(linux), not on the local one.
Local : Windows Xampp / PHP Version 5.6.3.

**Comment by mikehaertl** [comment]
Hmm, hard to tell, I don't use Windows for anything PHP at all.

Personal note: I very much recommend to use another setup for local development. Check out vagrant or  docker, so that you are closer to your server environment. Xampp is really the source of many evil (unless your server is also on windows). You have to mess around with problems that you never have in production.

**Comment by sebastienOD** [comment]
ok thx i'll try vagrant ! 
I spend too much time to find this pb.

**Comment by noobiwan** [comment]
As stated in the [manual](http://php.net/manual/en/function.escapeshellarg.php), 

> on Windows, escapeshellarg() instead replaces percent signs, exclamation marks (delayed variable substitution) and double quotes with spaces and adds double quotes around the string.

So the way around this is to not escape the argument or create a custom escaping function for windows since pdftk expects a % and that we can't change. If you trust your input, you could simply change the third parameter to false on:

https://github.com/mikehaertl/php-pdftk/blob/master/src/Command.php#L197
