### ISSUE TITLE
Sending pdf instance in mail

### ISSUE THREAD

**Issue by chris-verclytte** [mikehaertl/php-pdftk#42]
Hello @mikehaertl !
I am trying to send one generated pdf as an attachment in an email without having to save it on disk.
Is this possible ? 

I am currently using Symfony (with SwiftMailer) and I thought it would be possible to make something like this : 
 ```
    $pdf = new Pdf('...');
    $pdf->fillForm($array)
            ->needAppearances()
            ->flatten();
    $attachment = \Swift_Attachment::newInstance($pdf->getTmpFile(), $filename, 'application/pdf');
    $message = \Swift_Message::newInstance()
        ->setSubject('...')
        ->setFrom('...@...')
        ->setTo('...@...')
        ->setBody(...)
        ->attach($attachment);
        $this->get('mailer')->send($message);
```

Unfortunately, when I do this, I do have a pdf attachment but the file is corrupted. Am I misunderstanding the purpose of getTmpFile() ?

Thanks in advance !

**Comment by mikehaertl** [comment]
You need to call `execute()` on the `$pdf`. It may still fail though, because of this code:

https://github.com/mikehaertl/php-tmpfile/blob/master/src/File.php#L50

From the PHP manual:

> PHP 5 introduces a destructor concept similar to that of other object-oriented languages, such as C++. The destructor method will be called as soon as there are no other references to a particular object, or in any order during the shutdown sequence.

This is the case for you: There's no reference to `$pdf` after you've attached it to the email. So it's safer to save the file under some name, then unlink it after you've sent the email.

**Comment by chris-verclytte** [comment]
Ok I got it. Thanks a lot !
