### ISSUE TITLE
flatten() and needAppearances()

### ISSUE THREAD

**Issue by edgaraafelix** [mikehaertl/php-pdftk#53]
I need to use `flatten() ` in order to disable the form field after it's filled, but the documentation says that we can't combine this option with `needAppearances()`.

My question is why can't we combine both options?

Will the pdf render the field content properly if I stop using `needAppearances()`? By default my content is in UTF8.

Something like `à, ç, â, ã, é, Õ, nº`.. will still be rendered by a PDF reader?

**Comment by mikehaertl** [comment]
I don't think the documentation really says that. It just doesn't help much. When you "flatten" a PDF form, the field values are added to the PDF as full "PDF objects". Usually this should make sure, that all required font glyph data (e.g. for special characters) is embedded in the PDF itself. That's what make the PDF format so special: any client should find all the information required to render the PDF inside the PDF file.

Unfortunately the PDF library that pdftk is based on is not really good at this. If I remember correctly it will just leave away any special characters when flattening a PDF.

That's why the better option is *not* to flatten the PDF and set the [appearance](https://github.com/mikehaertl/php-pdftk/issues/4#issuecomment-59006225) flag. This only includes the field values (no font data!) into the PDF. And with appearance set, the PDF file basically says to the viewer: "Do whatever is neccessary to somehow render those crazy values!".

From my experience this works pretty well, even with UTF-8 characters.

I'm closing this for now, as it's not really an issue. At least nothing we can improve. pdftk is really somewhat limited here. And understanding the PDF format comes close to rocket science. So don't expect that all I said above is 100% correct. It's just what I've learned from writing this library.

**Comment by mikehaertl** [comment]
As a solution to your initial problem: You could try to change the PDF permissions after you've filled the form. So that it's forbidden to modify the form fields after you filled them. I've never done that so I'm not sure, if that works or if it's possible at all. But you can change permissions with this library. See the man page for pdftk.
